BerkmanAtlasViewerBundle_homepage:
    pattern: / 
    defaults: { _controller: BerkmanAtlasViewerBundle:Atlas:index }

BerkmanAtlasViewerBundle_atlas:
    resource: "@BerkmanAtlasViewerBundle/Resources/config/routing/atlas.yml"
    prefix:   /atlas

BerkmanAtlasViewerBundle_page:
    resource: "@BerkmanAtlasViewerBundle/Resources/config/routing/page.yml"
    prefix:   /page
