Berkman\AtlasViewerBundle\Entity\Atlas:
  type: entity
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    name:
      type: string
    description:
      type: text
      nullable: true
    created:
      type: datetime
    updated:
      type: datetime
  oneToMany:
    pages:
      targetEntity: Page
      mappedBy: atlas
      cascade: ["persist", "remove"] 
  manyToOne:
    owner:
      targetEntity: Person
      inversedBy: atlases
