Berkman\AtlasViewerBundle\Entity\Job:
  type: entity
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    command:
      type: string
    timeout:
      type: integer
