Berkman\AtlasViewerBundle\Entity\Page:
  type: entity
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    name:
      type: string
    epsg_code:
      type: integer
    metadata:
      type: array
    filename:
      type: string
      nullable: true
    bounding_box:
      type: array
      nullable: true
    min_zoom_level:
      type: integer
      nullable: true
    max_zoom_level:
      type: integer
      nullable: true
  manyToOne:
    atlas:
      targetEntity: Atlas
      inversedBy: pages
